CREATE DATABASE PUBLICAIONESLIBROS
GO


USE PUBLICAIONESLIBROS


CREATE TABLE Editorial(
	
	Id INT IDENTITY NOT NULL,
	CONsTRAINT PK_Editorial PRIMARY KEY (Id),
	Editorial VARCHAR (150) NOT NULL,

)



CREATE TABLE Pais(
	
	Id INT IDENTITY NOT NULL,
	CONsTRAINT PK_Pais PRIMARY KEY (Id),
	Pais VARCHAR (150) NOT NULL,

)



CREATE TABLE Tema(
	
	Id INT IDENTITY NOT NULL,
	CONsTRAINT PK_Tema PRIMARY KEY (Id),
	Tema VARCHAR (150) NOT NULL,

)




CREATE TABLE Libro(

	Id INT IDENTITY NOT NULL,
	CONSTRAINT PK_Libro PRIMARY KEY (Id),
	Titulo VARCHAR(150) NOT NULL,
	EDICION INT NOT NULL,
	AÑO INT NOT NULL,
	IdEditorial INT NOT NULL,
	CONSTRAINT FK_Libro_Editorial FOREIGN KEY (IdEditorial) REFERENCES Editorial(Id),
	Paginas INT NOT NULL,
	Signatura VARCHAR(200) NOT NULL,
	ISBN INT NOT NULL

)






CREATE TABLE Ciudad(
	
	Id INT IDENTITY NOT NULL,
	CONsTRAINT PK_Ciudad PRIMARY KEY (Id),
	Ciudad VARCHAR (150) NOT NULL,
	Idpais INT NOT NULL,
	CONSTRAINT FK_Ciudad_Pais FOREIGN KEY (IdPais) REFERENCES Pais(Id)

)







CREATE TABLE Autor(
	
	Id INT IDENTITY NOT NULL,
	CONsTRAINT PK_Autor PRIMARY KEY (Id),
	Nombre VARCHAR (150) NOT NULL,
	IdPais INT NOT NULL,
	CONSTRAINT FK_Autor_Pais FOREIGN KEY (IdPais) REFERENCES Pais(Id)

)



CREATE TABLE LibroAutor(
	IdLibro INT NOT NULL,
	CONSTRAINT FK_LibroAutor_IdLibro FOREIGN KEY (IdLibro) REFERENCES Libro(Id),
	IdAutor INT NOT NULL,	
	CONSTRAINT FK_LibroAutor_IdAutor FOREIGN KEY (IdAutor) REFERENCES Autor(Id)

)






CREATE TABLE LibroTema(
	IdLibro INT NOT NULL,
	CONSTRAINT FK_LibroTema_IdLibro FOREIGN KEY (IdLibro) REFERENCES Libro(Id),
	IdTema INT NOT NULL,	
	CONSTRAINT FK_LibroTema_IdAutor FOREIGN KEY (IdTema) REFERENCES Tema(Id)

)

